# Redis 主节点配置 (node-1)
bind 0.0.0.0
port 6379
protected-mode no

# 持久化
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfsync everysec
appendfilename "appendonly.aof"

# 复制
replica-announce-ip 192.168.0.102
replica-announce-port 6379

# 内存
maxmemory 4gb
maxmemory-policy allkeys-lru

# 日志
loglevel notice
logfile "/data/redis.log"
