// boss/common/v1 —— 跨服务公共契约(错误码/分页/事件 envelope)。
// 契约先行(见 docs/ADR-001 第4条、architecture-review 发现 2.1):
//   - 每个跨服务域对应一个 proto 模块(syntax proto3, package 以 boss.<domain>.vN 命名);
//   - 对外 REST 由 api/openapi 描述,APISIX 按两者生成路由,服务内 gRPC 复用同一语义;
//   - 版本变更只加字段、不破坏已有字段编号,破坏性变更升 vN。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: api/proto/boss/common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Code 统一错误码,与服务端 pkg/apitypes.Code 数值对齐(跨语言共享语义)。
type Code int32

const (
	Code_CODE_OK             Code = 0
	Code_CODE_INTERNAL       Code = 50000
	Code_CODE_UNAUTHORIZED   Code = 40100
	Code_CODE_FORBIDDEN      Code = 40300
	Code_CODE_NOT_FOUND      Code = 40400
	Code_CODE_CONFLICT       Code = 40900
	Code_CODE_INVALID_PARAM  Code = 42200
	Code_CODE_RESOURCE_BUSY  Code = 42300
	Code_CODE_STATE_INVALID  Code = 40910
	Code_CODE_SCAN_MISMATCH  Code = 40920
	Code_CODE_DOWNSTREAM_ERR Code = 50200
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:     "CODE_OK",
		50000: "CODE_INTERNAL",
		40100: "CODE_UNAUTHORIZED",
		40300: "CODE_FORBIDDEN",
		40400: "CODE_NOT_FOUND",
		40900: "CODE_CONFLICT",
		42200: "CODE_INVALID_PARAM",
		42300: "CODE_RESOURCE_BUSY",
		40910: "CODE_STATE_INVALID",
		40920: "CODE_SCAN_MISMATCH",
		50200: "CODE_DOWNSTREAM_ERR",
	}
	Code_value = map[string]int32{
		"CODE_OK":             0,
		"CODE_INTERNAL":       50000,
		"CODE_UNAUTHORIZED":   40100,
		"CODE_FORBIDDEN":      40300,
		"CODE_NOT_FOUND":      40400,
		"CODE_CONFLICT":       40900,
		"CODE_INVALID_PARAM":  42200,
		"CODE_RESOURCE_BUSY":  42300,
		"CODE_STATE_INVALID":  40910,
		"CODE_SCAN_MISMATCH":  40920,
		"CODE_DOWNSTREAM_ERR": 50200,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_boss_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_api_proto_boss_common_v1_common_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_boss_common_v1_common_proto_rawDescGZIP(), []int{0}
}

// Error 服务间统一错误对象;msg 面向人,detail 可承载结构化上下文。
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=boss.common.v1.Code" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Detail        map[string]string      `protobuf:"bytes,3,rep,name=detail,proto3" json:"detail,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_api_proto_boss_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_CODE_OK
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Error) GetDetail() map[string]string {
	if x != nil {
		return x.Detail
	}
	return nil
}

// PageRequest 通用分页请求。
type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 1-based
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 上限由服务端约定,超限时裁剪
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_api_proto_boss_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// PageResponse 通用分页响应。
type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_api_proto_boss_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *PageResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_proto_boss_common_v1_common_proto protoreflect.FileDescriptor

const file_api_proto_boss_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"%api/proto/boss/common/v1/common.proto\x12\x0eboss.common.v1\"\xb9\x01\n" +
	"\x05Error\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.boss.common.v1.CodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x129\n" +
	"\x06detail\x18\x03 \x03(\v2!.boss.common.v1.Error.DetailEntryR\x06detail\x1a9\n" +
	"\vDetailEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\vPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"U\n" +
	"\fPageResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total*\x85\x02\n" +
	"\x04Code\x12\v\n" +
	"\aCODE_OK\x10\x00\x12\x13\n" +
	"\rCODE_INTERNAL\x10І\x03\x12\x17\n" +
	"\x11CODE_UNAUTHORIZED\x10\xa4\xb9\x02\x12\x14\n" +
	"\x0eCODE_FORBIDDEN\x10\xec\xba\x02\x12\x14\n" +
	"\x0eCODE_NOT_FOUND\x10л\x02\x12\x13\n" +
	"\rCODE_CONFLICT\x10Ŀ\x02\x12\x18\n" +
	"\x12CODE_INVALID_PARAM\x10\xd8\xc9\x02\x12\x18\n" +
	"\x12CODE_RESOURCE_BUSY\x10\xbc\xca\x02\x12\x18\n" +
	"\x12CODE_STATE_INVALID\x10ο\x02\x12\x18\n" +
	"\x12CODE_SCAN_MISMATCH\x10ؿ\x02\x12\x19\n" +
	"\x13CODE_DOWNSTREAM_ERR\x10\x98\x88\x03B;Z9github.com/ymm-001/boss/api/proto/boss/common/v1;commonv1b\x06proto3"

var (
	file_api_proto_boss_common_v1_common_proto_rawDescOnce sync.Once
	file_api_proto_boss_common_v1_common_proto_rawDescData []byte
)

func file_api_proto_boss_common_v1_common_proto_rawDescGZIP() []byte {
	file_api_proto_boss_common_v1_common_proto_rawDescOnce.Do(func() {
		file_api_proto_boss_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_boss_common_v1_common_proto_rawDesc), len(file_api_proto_boss_common_v1_common_proto_rawDesc)))
	})
	return file_api_proto_boss_common_v1_common_proto_rawDescData
}

var file_api_proto_boss_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_boss_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_boss_common_v1_common_proto_goTypes = []any{
	(Code)(0),            // 0: boss.common.v1.Code
	(*Error)(nil),        // 1: boss.common.v1.Error
	(*PageRequest)(nil),  // 2: boss.common.v1.PageRequest
	(*PageResponse)(nil), // 3: boss.common.v1.PageResponse
	nil,                  // 4: boss.common.v1.Error.DetailEntry
}
var file_api_proto_boss_common_v1_common_proto_depIdxs = []int32{
	0, // 0: boss.common.v1.Error.code:type_name -> boss.common.v1.Code
	4, // 1: boss.common.v1.Error.detail:type_name -> boss.common.v1.Error.DetailEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_boss_common_v1_common_proto_init() }
func file_api_proto_boss_common_v1_common_proto_init() {
	if File_api_proto_boss_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_boss_common_v1_common_proto_rawDesc), len(file_api_proto_boss_common_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_boss_common_v1_common_proto_goTypes,
		DependencyIndexes: file_api_proto_boss_common_v1_common_proto_depIdxs,
		EnumInfos:         file_api_proto_boss_common_v1_common_proto_enumTypes,
		MessageInfos:      file_api_proto_boss_common_v1_common_proto_msgTypes,
	}.Build()
	File_api_proto_boss_common_v1_common_proto = out.File
	file_api_proto_boss_common_v1_common_proto_goTypes = nil
	file_api_proto_boss_common_v1_common_proto_depIdxs = nil
}
