// genrouteperms 从 internal/httpapi/admin 的 gin 路由注册源码提取「路由 → permCode」映射,
// 生成 internal/apiroutes/admin_perms_gen.go;admin 端 MCP 目录按当前账号权限过滤的数据源。
//
// 机理:requirePerm(a.User, "menu:x") 是唯一的 RBAC 门禁装配点(包内唯一包一层 Authz),
// 以 AST 解析路由注册(内联/var/组级/跨 register 函数传组与 perm)可得每条路由的权限码全集;
// openapi 只描述路由,不含权限,故此映射必须来自 Go 源码这一事实源。
//
// 用法: go run ./scripts/genrouteperms          (仓库根执行,写盘)
//       go run ./scripts/genrouteperms --check  (内存比对不写盘,漂移 exit 1;进 make check)
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	check := false
	for _, a := range os.Args[1:] {
		if a == "--check" {
			check = true
		}
	}
	out, err := run()
	if err != nil {
		fmt.Fprintf(os.Stderr, "[genrouteperms] FAILED: %v\n", err)
		os.Exit(1)
	}
	if err := emit(out, check); err != nil {
		fmt.Fprintf(os.Stderr, "[genrouteperms] FAILED: %v\n", err)
		os.Exit(1)
	}
}

// run 提取全部路由并渲染生成文件内容。
func run() (string, error) {
	g, err := newGen(adminDir())
	if err != nil {
		return "", err
	}
	if err := g.extract(); err != nil {
		return "", err
	}
	if len(g.routes) == 0 {
		return "", fmt.Errorf("提取到 0 条路由,解析逻辑与源码结构脱节")
	}
	return render(g.sortedRoutes()), nil
}

// adminDir 定位 admin 路由注册源码目录(生成物与源码同仓,取脚本所在仓根)。
func adminDir() string {
	wd, err := os.Getwd()
	if err != nil {
		return "internal/httpapi/admin"
	}
	return filepath.Join(wd, "internal", "httpapi", "admin")
}

// outPath 生成物路径。
func outPath() string {
	wd, _ := os.Getwd()
	return filepath.Join(wd, "internal", "apiroutes", "admin_perms_gen.go")
}

// emit 写盘或 --check 内存比对;漂移即失败(权限语义变更后忘了再生成在此拦截)。
func emit(content string, check bool) error {
	path := outPath()
	if check {
		disk, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}
		if string(disk) != content {
			return fmt.Errorf("DRIFT %s: 与 internal/httpapi/admin 不一致,执行 go run ./scripts/genrouteperms 后随变更同提交", path)
		}
		fmt.Printf("CHECK OK %s: %d 条路由\n", path, strings.Count(content, "\t\""))
		return nil
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	fmt.Printf("%s: %d 条路由\n", path, strings.Count(content, "\t\""))
	return nil
}

// render 渲染生成文件:路由键字典序 + 码集字典序,保证幂等(--check 可比对)。
func render(routes [][2]any) string {
	var b strings.Builder
	b.WriteString("// Code generated by scripts/genrouteperms from internal/httpapi/admin; DO NOT EDIT.\n")
	b.WriteString("// admin 端「路由 → permCode」映射(requirePerm 门禁的静态投影,gin :param 已转 {param}),\n")
	b.WriteString("// bossmcp admin 目录按当前账号权限过滤的数据源。再生成: go run ./scripts/genrouteperms\n\n")
	b.WriteString("package apiroutes\n\n")
	b.WriteString("// AdminRoutePerms 路由键(方法 空格 路径)→ 权限码全集(须全部持有;空集=仅认证,无菜单门禁)。\n")
	b.WriteString("// 同路由多注册分支取并集:任一分支要求某码即保留,防止目录面超发。\n")
	b.WriteString("var AdminRoutePerms = map[string][]string{\n")
	for _, kv := range routes {
		key := kv[0].(string)
		codes := kv[1].([]string)
		quoted := make([]string, len(codes))
		for i, c := range codes {
			quoted[i] = fmt.Sprintf("%q", c)
		}
		if len(quoted) == 0 {
			fmt.Fprintf(&b, "\t%q: {},\n", key)
			continue
		}
		fmt.Fprintf(&b, "\t%q: {%s},\n", key, strings.Join(quoted, ", "))
	}
	b.WriteString("}\n")
	return b.String()
}
