BEGIN;
DROP TABLE IF EXISTS user_bill_items;
DROP TABLE IF EXISTS product_specs;
DROP TABLE IF EXISTS user_verify_records;
DROP TABLE IF EXISTS user_complaints;
DROP TABLE IF EXISTS user_invoices;
DROP TABLE IF EXISTS topup_denominations;
DROP TABLE IF EXISTS user_balances;
DROP TABLE IF EXISTS agreements;
DROP TABLE IF EXISTS diy_guides;
DROP TABLE IF EXISTS user_usages;
DROP TABLE IF EXISTS invite_config;
DROP TABLE IF EXISTS coupons;
DROP TABLE IF EXISTS user_messages;
DROP TABLE IF EXISTS user_faqs;
DROP TABLE IF EXISTS user_notify_settings;
DROP TABLE IF EXISTS addon_subscriptions;
DROP TABLE IF EXISTS addons;
DROP TABLE IF EXISTS user_plans;
DROP TABLE IF EXISTS user_addresses;
DROP TABLE IF EXISTS user_accounts;
COMMIT;
