BEGIN;
ALTER TABLE accounts
    DROP COLUMN IF EXISTS region_scope,
    DROP COLUMN IF EXISTS post_id,
    DROP COLUMN IF EXISTS dept_id,
    DROP COLUMN IF EXISTS legal_entity_id;
DROP TABLE IF EXISTS post_roles CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS legal_entities CASCADE;
DROP TABLE IF EXISTS regions CASCADE;
COMMIT;
