-- 000191 down: 刻意为空(P4-T2 Lead 裁定 2026-09-06)。
-- '光猫'→'ONU' 是不可逆的方言归一裁定:权威类型码为 ONU,down 若把 ONU 行
-- 回写'光猫'等于复活已裁定的历史方言,并会把裁定前本就是 ONU 的存量一并污染
-- (两群行在 UPDATE 后不可区分)。如需回滚本迁移,必须连同白名单
-- (internal/domain/asset/type_whitelist.go)与 fields.md §4.1 契约一并人工裁定,
-- 不提供自动回滚路径。
