-- 000203 down:回退 SMALLINT(仅当无超 32767 数据时可行)。
BEGIN;

ALTER TABLE ports ALTER COLUMN tr069_cvlan    TYPE SMALLINT;
ALTER TABLE ports ALTER COLUMN internet_cvlan TYPE SMALLINT;
ALTER TABLE ports ALTER COLUMN cvlan          TYPE SMALLINT;
ALTER TABLE ports ALTER COLUMN svlan          TYPE SMALLINT;

COMMIT;
