// boss/device/v1 —— 设备指标上报契约(collector→server,阶段7/W7)。
// 语义:OLT/ONU 指标批量上报、Trap 告警实时推送。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/boss/device/v1/device.proto

package devicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceIngestService_ReportMetrics_FullMethodName = "/boss.device.v1.DeviceIngestService/ReportMetrics"
	DeviceIngestService_ReportTrap_FullMethodName    = "/boss.device.v1.DeviceIngestService/ReportTrap"
)

// DeviceIngestServiceClient is the client API for DeviceIngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeviceIngestService 设备采集上报服务。
type DeviceIngestServiceClient interface {
	// ReportMetrics SNMP 周期指标批量上报。
	ReportMetrics(ctx context.Context, in *ReportMetricsRequest, opts ...grpc.CallOption) (*OpResponse, error)
	// ReportTrap Trap 告警实时上报(触发告警规则)。
	ReportTrap(ctx context.Context, in *Trap, opts ...grpc.CallOption) (*OpResponse, error)
}

type deviceIngestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceIngestServiceClient(cc grpc.ClientConnInterface) DeviceIngestServiceClient {
	return &deviceIngestServiceClient{cc}
}

func (c *deviceIngestServiceClient) ReportMetrics(ctx context.Context, in *ReportMetricsRequest, opts ...grpc.CallOption) (*OpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResponse)
	err := c.cc.Invoke(ctx, DeviceIngestService_ReportMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceIngestServiceClient) ReportTrap(ctx context.Context, in *Trap, opts ...grpc.CallOption) (*OpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResponse)
	err := c.cc.Invoke(ctx, DeviceIngestService_ReportTrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceIngestServiceServer is the server API for DeviceIngestService service.
// All implementations must embed UnimplementedDeviceIngestServiceServer
// for forward compatibility.
//
// DeviceIngestService 设备采集上报服务。
type DeviceIngestServiceServer interface {
	// ReportMetrics SNMP 周期指标批量上报。
	ReportMetrics(context.Context, *ReportMetricsRequest) (*OpResponse, error)
	// ReportTrap Trap 告警实时上报(触发告警规则)。
	ReportTrap(context.Context, *Trap) (*OpResponse, error)
	mustEmbedUnimplementedDeviceIngestServiceServer()
}

// UnimplementedDeviceIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceIngestServiceServer struct{}

func (UnimplementedDeviceIngestServiceServer) ReportMetrics(context.Context, *ReportMetricsRequest) (*OpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportMetrics not implemented")
}
func (UnimplementedDeviceIngestServiceServer) ReportTrap(context.Context, *Trap) (*OpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTrap not implemented")
}
func (UnimplementedDeviceIngestServiceServer) mustEmbedUnimplementedDeviceIngestServiceServer() {}
func (UnimplementedDeviceIngestServiceServer) testEmbeddedByValue()                             {}

// UnsafeDeviceIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceIngestServiceServer will
// result in compilation errors.
type UnsafeDeviceIngestServiceServer interface {
	mustEmbedUnimplementedDeviceIngestServiceServer()
}

func RegisterDeviceIngestServiceServer(s grpc.ServiceRegistrar, srv DeviceIngestServiceServer) {
	// If the following call panics, it indicates UnimplementedDeviceIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceIngestService_ServiceDesc, srv)
}

func _DeviceIngestService_ReportMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceIngestServiceServer).ReportMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceIngestService_ReportMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceIngestServiceServer).ReportMetrics(ctx, req.(*ReportMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceIngestService_ReportTrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Trap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceIngestServiceServer).ReportTrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceIngestService_ReportTrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceIngestServiceServer).ReportTrap(ctx, req.(*Trap))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceIngestService_ServiceDesc is the grpc.ServiceDesc for DeviceIngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceIngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "boss.device.v1.DeviceIngestService",
	HandlerType: (*DeviceIngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportMetrics",
			Handler:    _DeviceIngestService_ReportMetrics_Handler,
		},
		{
			MethodName: "ReportTrap",
			Handler:    _DeviceIngestService_ReportTrap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/boss/device/v1/device.proto",
}
