// boss/device/v1 —— 设备指标上报契约(collector→server,阶段7/W7)。
// 语义:OLT/ONU 指标批量上报、Trap 告警实时推送。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: api/proto/boss/device/v1/device.proto

package devicev1

import (
	v1 "github.com/ymm-001/boss/api/proto/boss/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*MetricSample        `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMetricsRequest) Reset() {
	*x = ReportMetricsRequest{}
	mi := &file_api_proto_boss_device_v1_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMetricsRequest) ProtoMessage() {}

func (x *ReportMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_device_v1_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMetricsRequest.ProtoReflect.Descriptor instead.
func (*ReportMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_device_v1_device_proto_rawDescGZIP(), []int{0}
}

func (x *ReportMetricsRequest) GetSamples() []*MetricSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type MetricSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceCode  string                 `protobuf:"bytes,1,opt,name=resource_code,json=resourceCode,proto3" json:"resource_code,omitempty"`                                             // OLT-01 / ONU-...
	Gauges        map[string]float64     `protobuf:"bytes,2,rep,name=gauges,proto3" json:"gauges,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // cpu / mem /光功率/丢包率
	CollectedAt   int64                  `protobuf:"varint,3,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`                                               // unix 秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSample) Reset() {
	*x = MetricSample{}
	mi := &file_api_proto_boss_device_v1_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSample) ProtoMessage() {}

func (x *MetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_device_v1_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSample.ProtoReflect.Descriptor instead.
func (*MetricSample) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_device_v1_device_proto_rawDescGZIP(), []int{1}
}

func (x *MetricSample) GetResourceCode() string {
	if x != nil {
		return x.ResourceCode
	}
	return ""
}

func (x *MetricSample) GetGauges() map[string]float64 {
	if x != nil {
		return x.Gauges
	}
	return nil
}

func (x *MetricSample) GetCollectedAt() int64 {
	if x != nil {
		return x.CollectedAt
	}
	return 0
}

type Trap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceCode  string                 `protobuf:"bytes,1,opt,name=resource_code,json=resourceCode,proto3" json:"resource_code,omitempty"`
	Oid           string                 `protobuf:"bytes,2,opt,name=oid,proto3" json:"oid,omitempty"`
	Vars          map[string]string      `protobuf:"bytes,3,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TrappedAt     int64                  `protobuf:"varint,4,opt,name=trapped_at,json=trappedAt,proto3" json:"trapped_at,omitempty"`
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"` // INFO / WARNING / CRITICAL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trap) Reset() {
	*x = Trap{}
	mi := &file_api_proto_boss_device_v1_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trap) ProtoMessage() {}

func (x *Trap) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_device_v1_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trap.ProtoReflect.Descriptor instead.
func (*Trap) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_device_v1_device_proto_rawDescGZIP(), []int{2}
}

func (x *Trap) GetResourceCode() string {
	if x != nil {
		return x.ResourceCode
	}
	return ""
}

func (x *Trap) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *Trap) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *Trap) GetTrappedAt() int64 {
	if x != nil {
		return x.TrappedAt
	}
	return 0
}

func (x *Trap) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type OpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          v1.Code                `protobuf:"varint,1,opt,name=code,proto3,enum=boss.common.v1.Code" json:"code,omitempty"`
	Accepted      int32                  `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpResponse) Reset() {
	*x = OpResponse{}
	mi := &file_api_proto_boss_device_v1_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpResponse) ProtoMessage() {}

func (x *OpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_device_v1_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpResponse.ProtoReflect.Descriptor instead.
func (*OpResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_device_v1_device_proto_rawDescGZIP(), []int{3}
}

func (x *OpResponse) GetCode() v1.Code {
	if x != nil {
		return x.Code
	}
	return v1.Code(0)
}

func (x *OpResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

var File_api_proto_boss_device_v1_device_proto protoreflect.FileDescriptor

const file_api_proto_boss_device_v1_device_proto_rawDesc = "" +
	"\n" +
	"%api/proto/boss/device/v1/device.proto\x12\x0eboss.device.v1\x1a%api/proto/boss/common/v1/common.proto\"N\n" +
	"\x14ReportMetricsRequest\x126\n" +
	"\asamples\x18\x01 \x03(\v2\x1c.boss.device.v1.MetricSampleR\asamples\"\xd3\x01\n" +
	"\fMetricSample\x12#\n" +
	"\rresource_code\x18\x01 \x01(\tR\fresourceCode\x12@\n" +
	"\x06gauges\x18\x02 \x03(\v2(.boss.device.v1.MetricSample.GaugesEntryR\x06gauges\x12!\n" +
	"\fcollected_at\x18\x03 \x01(\x03R\vcollectedAt\x1a9\n" +
	"\vGaugesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xe5\x01\n" +
	"\x04Trap\x12#\n" +
	"\rresource_code\x18\x01 \x01(\tR\fresourceCode\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\tR\x03oid\x122\n" +
	"\x04vars\x18\x03 \x03(\v2\x1e.boss.device.v1.Trap.VarsEntryR\x04vars\x12\x1d\n" +
	"\n" +
	"trapped_at\x18\x04 \x01(\x03R\ttrappedAt\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\n" +
	"OpResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.boss.common.v1.CodeR\x04code\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\x05R\baccepted2\xa8\x01\n" +
	"\x13DeviceIngestService\x12Q\n" +
	"\rReportMetrics\x12$.boss.device.v1.ReportMetricsRequest\x1a\x1a.boss.device.v1.OpResponse\x12>\n" +
	"\n" +
	"ReportTrap\x12\x14.boss.device.v1.Trap\x1a\x1a.boss.device.v1.OpResponseB;Z9github.com/ymm-001/boss/api/proto/boss/device/v1;devicev1b\x06proto3"

var (
	file_api_proto_boss_device_v1_device_proto_rawDescOnce sync.Once
	file_api_proto_boss_device_v1_device_proto_rawDescData []byte
)

func file_api_proto_boss_device_v1_device_proto_rawDescGZIP() []byte {
	file_api_proto_boss_device_v1_device_proto_rawDescOnce.Do(func() {
		file_api_proto_boss_device_v1_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_boss_device_v1_device_proto_rawDesc), len(file_api_proto_boss_device_v1_device_proto_rawDesc)))
	})
	return file_api_proto_boss_device_v1_device_proto_rawDescData
}

var file_api_proto_boss_device_v1_device_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_boss_device_v1_device_proto_goTypes = []any{
	(*ReportMetricsRequest)(nil), // 0: boss.device.v1.ReportMetricsRequest
	(*MetricSample)(nil),         // 1: boss.device.v1.MetricSample
	(*Trap)(nil),                 // 2: boss.device.v1.Trap
	(*OpResponse)(nil),           // 3: boss.device.v1.OpResponse
	nil,                          // 4: boss.device.v1.MetricSample.GaugesEntry
	nil,                          // 5: boss.device.v1.Trap.VarsEntry
	(v1.Code)(0),                 // 6: boss.common.v1.Code
}
var file_api_proto_boss_device_v1_device_proto_depIdxs = []int32{
	1, // 0: boss.device.v1.ReportMetricsRequest.samples:type_name -> boss.device.v1.MetricSample
	4, // 1: boss.device.v1.MetricSample.gauges:type_name -> boss.device.v1.MetricSample.GaugesEntry
	5, // 2: boss.device.v1.Trap.vars:type_name -> boss.device.v1.Trap.VarsEntry
	6, // 3: boss.device.v1.OpResponse.code:type_name -> boss.common.v1.Code
	0, // 4: boss.device.v1.DeviceIngestService.ReportMetrics:input_type -> boss.device.v1.ReportMetricsRequest
	2, // 5: boss.device.v1.DeviceIngestService.ReportTrap:input_type -> boss.device.v1.Trap
	3, // 6: boss.device.v1.DeviceIngestService.ReportMetrics:output_type -> boss.device.v1.OpResponse
	3, // 7: boss.device.v1.DeviceIngestService.ReportTrap:output_type -> boss.device.v1.OpResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_boss_device_v1_device_proto_init() }
func file_api_proto_boss_device_v1_device_proto_init() {
	if File_api_proto_boss_device_v1_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_boss_device_v1_device_proto_rawDesc), len(file_api_proto_boss_device_v1_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_boss_device_v1_device_proto_goTypes,
		DependencyIndexes: file_api_proto_boss_device_v1_device_proto_depIdxs,
		MessageInfos:      file_api_proto_boss_device_v1_device_proto_msgTypes,
	}.Build()
	File_api_proto_boss_device_v1_device_proto = out.File
	file_api_proto_boss_device_v1_device_proto_goTypes = nil
	file_api_proto_boss_device_v1_device_proto_depIdxs = nil
}
