// boss/provision/v1 —— 配置下发契约(order→provisioner,阶段7/W7-W8)。
// 语义:模板/任务下发、失败重试、环节自动化(6/7/10/11)。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/boss/provision/v1/provision.proto

package provisionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProvisionService_EnqueueTask_FullMethodName = "/boss.provision.v1.ProvisionService/EnqueueTask"
	ProvisionService_RetryTask_FullMethodName   = "/boss.provision.v1.ProvisionService/RetryTask"
	ProvisionService_GetTask_FullMethodName     = "/boss.provision.v1.ProvisionService/GetTask"
)

// ProvisionServiceClient is the client API for ProvisionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProvisionService 配置下发服务。
type ProvisionServiceClient interface {
	// EnqueueTask 下发任务入队(环节7 preConfigOLT / 环节10 激活 / 环节11 通知)。
	EnqueueTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*OpResponse, error)
	// RetryTask 失败重试(留痕:重试次数计入任务日志)。
	RetryTask(ctx context.Context, in *RetryTaskRequest, opts ...grpc.CallOption) (*OpResponse, error)
	// GetTask 任务状态查询(轮询/回调校验)。
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
}

type provisionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProvisionServiceClient(cc grpc.ClientConnInterface) ProvisionServiceClient {
	return &provisionServiceClient{cc}
}

func (c *provisionServiceClient) EnqueueTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*OpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResponse)
	err := c.cc.Invoke(ctx, ProvisionService_EnqueueTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionServiceClient) RetryTask(ctx context.Context, in *RetryTaskRequest, opts ...grpc.CallOption) (*OpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResponse)
	err := c.cc.Invoke(ctx, ProvisionService_RetryTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, ProvisionService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvisionServiceServer is the server API for ProvisionService service.
// All implementations must embed UnimplementedProvisionServiceServer
// for forward compatibility.
//
// ProvisionService 配置下发服务。
type ProvisionServiceServer interface {
	// EnqueueTask 下发任务入队(环节7 preConfigOLT / 环节10 激活 / 环节11 通知)。
	EnqueueTask(context.Context, *Task) (*OpResponse, error)
	// RetryTask 失败重试(留痕:重试次数计入任务日志)。
	RetryTask(context.Context, *RetryTaskRequest) (*OpResponse, error)
	// GetTask 任务状态查询(轮询/回调校验)。
	GetTask(context.Context, *GetTaskRequest) (*Task, error)
	mustEmbedUnimplementedProvisionServiceServer()
}

// UnimplementedProvisionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProvisionServiceServer struct{}

func (UnimplementedProvisionServiceServer) EnqueueTask(context.Context, *Task) (*OpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueTask not implemented")
}
func (UnimplementedProvisionServiceServer) RetryTask(context.Context, *RetryTaskRequest) (*OpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryTask not implemented")
}
func (UnimplementedProvisionServiceServer) GetTask(context.Context, *GetTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedProvisionServiceServer) mustEmbedUnimplementedProvisionServiceServer() {}
func (UnimplementedProvisionServiceServer) testEmbeddedByValue()                          {}

// UnsafeProvisionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProvisionServiceServer will
// result in compilation errors.
type UnsafeProvisionServiceServer interface {
	mustEmbedUnimplementedProvisionServiceServer()
}

func RegisterProvisionServiceServer(s grpc.ServiceRegistrar, srv ProvisionServiceServer) {
	// If the following call panics, it indicates UnimplementedProvisionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProvisionService_ServiceDesc, srv)
}

func _ProvisionService_EnqueueTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServiceServer).EnqueueTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvisionService_EnqueueTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServiceServer).EnqueueTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionService_RetryTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServiceServer).RetryTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvisionService_RetryTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServiceServer).RetryTask(ctx, req.(*RetryTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvisionService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProvisionService_ServiceDesc is the grpc.ServiceDesc for ProvisionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProvisionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "boss.provision.v1.ProvisionService",
	HandlerType: (*ProvisionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnqueueTask",
			Handler:    _ProvisionService_EnqueueTask_Handler,
		},
		{
			MethodName: "RetryTask",
			Handler:    _ProvisionService_RetryTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _ProvisionService_GetTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/boss/provision/v1/provision.proto",
}
