// boss/provision/v1 —— 配置下发契约(order→provisioner,阶段7/W7-W8)。
// 语义:模板/任务下发、失败重试、环节自动化(6/7/10/11)。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: api/proto/boss/provision/v1/provision.proto

package provisionv1

import (
	v1 "github.com/ymm-001/boss/api/proto/boss/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TaskNo        string                 `protobuf:"bytes,2,opt,name=task_no,json=taskNo,proto3" json:"task_no,omitempty"`
	StageEvent    string                 `protobuf:"bytes,3,opt,name=stage_event,json=stageEvent,proto3" json:"stage_event,omitempty"` // preConfigOLT / activateUser / notifyActivation
	TemplateCode  string                 `protobuf:"bytes,4,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	Params        map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_proto_boss_provision_v1_provision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_provision_v1_provision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_provision_v1_provision_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Task) GetTaskNo() string {
	if x != nil {
		return x.TaskNo
	}
	return ""
}

func (x *Task) GetStageEvent() string {
	if x != nil {
		return x.StageEvent
	}
	return ""
}

func (x *Task) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *Task) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type RetryTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskNo        string                 `protobuf:"bytes,1,opt,name=task_no,json=taskNo,proto3" json:"task_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryTaskRequest) Reset() {
	*x = RetryTaskRequest{}
	mi := &file_api_proto_boss_provision_v1_provision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskRequest) ProtoMessage() {}

func (x *RetryTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_provision_v1_provision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskRequest.ProtoReflect.Descriptor instead.
func (*RetryTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_provision_v1_provision_proto_rawDescGZIP(), []int{1}
}

func (x *RetryTaskRequest) GetTaskNo() string {
	if x != nil {
		return x.TaskNo
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskNo        string                 `protobuf:"bytes,1,opt,name=task_no,json=taskNo,proto3" json:"task_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_proto_boss_provision_v1_provision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_provision_v1_provision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_provision_v1_provision_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetTaskNo() string {
	if x != nil {
		return x.TaskNo
	}
	return ""
}

type OpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          v1.Code                `protobuf:"varint,1,opt,name=code,proto3,enum=boss.common.v1.Code" json:"code,omitempty"`
	TaskNo        string                 `protobuf:"bytes,2,opt,name=task_no,json=taskNo,proto3" json:"task_no,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // PENDING / DOING / DONE / FAILED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpResponse) Reset() {
	*x = OpResponse{}
	mi := &file_api_proto_boss_provision_v1_provision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpResponse) ProtoMessage() {}

func (x *OpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_provision_v1_provision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpResponse.ProtoReflect.Descriptor instead.
func (*OpResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_provision_v1_provision_proto_rawDescGZIP(), []int{3}
}

func (x *OpResponse) GetCode() v1.Code {
	if x != nil {
		return x.Code
	}
	return v1.Code(0)
}

func (x *OpResponse) GetTaskNo() string {
	if x != nil {
		return x.TaskNo
	}
	return ""
}

func (x *OpResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_proto_boss_provision_v1_provision_proto protoreflect.FileDescriptor

const file_api_proto_boss_provision_v1_provision_proto_rawDesc = "" +
	"\n" +
	"+api/proto/boss/provision/v1/provision.proto\x12\x11boss.provision.v1\x1a%api/proto/boss/common/v1/common.proto\"\xf8\x01\n" +
	"\x04Task\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x17\n" +
	"\atask_no\x18\x02 \x01(\tR\x06taskNo\x12\x1f\n" +
	"\vstage_event\x18\x03 \x01(\tR\n" +
	"stageEvent\x12#\n" +
	"\rtemplate_code\x18\x04 \x01(\tR\ftemplateCode\x12;\n" +
	"\x06params\x18\x05 \x03(\v2#.boss.provision.v1.Task.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\x10RetryTaskRequest\x12\x17\n" +
	"\atask_no\x18\x01 \x01(\tR\x06taskNo\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_no\x18\x01 \x01(\tR\x06taskNo\"g\n" +
	"\n" +
	"OpResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.boss.common.v1.CodeR\x04code\x12\x17\n" +
	"\atask_no\x18\x02 \x01(\tR\x06taskNo\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\xf1\x01\n" +
	"\x10ProvisionService\x12E\n" +
	"\vEnqueueTask\x12\x17.boss.provision.v1.Task\x1a\x1d.boss.provision.v1.OpResponse\x12O\n" +
	"\tRetryTask\x12#.boss.provision.v1.RetryTaskRequest\x1a\x1d.boss.provision.v1.OpResponse\x12E\n" +
	"\aGetTask\x12!.boss.provision.v1.GetTaskRequest\x1a\x17.boss.provision.v1.TaskBAZ?github.com/ymm-001/boss/api/proto/boss/provision/v1;provisionv1b\x06proto3"

var (
	file_api_proto_boss_provision_v1_provision_proto_rawDescOnce sync.Once
	file_api_proto_boss_provision_v1_provision_proto_rawDescData []byte
)

func file_api_proto_boss_provision_v1_provision_proto_rawDescGZIP() []byte {
	file_api_proto_boss_provision_v1_provision_proto_rawDescOnce.Do(func() {
		file_api_proto_boss_provision_v1_provision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_boss_provision_v1_provision_proto_rawDesc), len(file_api_proto_boss_provision_v1_provision_proto_rawDesc)))
	})
	return file_api_proto_boss_provision_v1_provision_proto_rawDescData
}

var file_api_proto_boss_provision_v1_provision_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_boss_provision_v1_provision_proto_goTypes = []any{
	(*Task)(nil),             // 0: boss.provision.v1.Task
	(*RetryTaskRequest)(nil), // 1: boss.provision.v1.RetryTaskRequest
	(*GetTaskRequest)(nil),   // 2: boss.provision.v1.GetTaskRequest
	(*OpResponse)(nil),       // 3: boss.provision.v1.OpResponse
	nil,                      // 4: boss.provision.v1.Task.ParamsEntry
	(v1.Code)(0),             // 5: boss.common.v1.Code
}
var file_api_proto_boss_provision_v1_provision_proto_depIdxs = []int32{
	4, // 0: boss.provision.v1.Task.params:type_name -> boss.provision.v1.Task.ParamsEntry
	5, // 1: boss.provision.v1.OpResponse.code:type_name -> boss.common.v1.Code
	0, // 2: boss.provision.v1.ProvisionService.EnqueueTask:input_type -> boss.provision.v1.Task
	1, // 3: boss.provision.v1.ProvisionService.RetryTask:input_type -> boss.provision.v1.RetryTaskRequest
	2, // 4: boss.provision.v1.ProvisionService.GetTask:input_type -> boss.provision.v1.GetTaskRequest
	3, // 5: boss.provision.v1.ProvisionService.EnqueueTask:output_type -> boss.provision.v1.OpResponse
	3, // 6: boss.provision.v1.ProvisionService.RetryTask:output_type -> boss.provision.v1.OpResponse
	0, // 7: boss.provision.v1.ProvisionService.GetTask:output_type -> boss.provision.v1.Task
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_boss_provision_v1_provision_proto_init() }
func file_api_proto_boss_provision_v1_provision_proto_init() {
	if File_api_proto_boss_provision_v1_provision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_boss_provision_v1_provision_proto_rawDesc), len(file_api_proto_boss_provision_v1_provision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_boss_provision_v1_provision_proto_goTypes,
		DependencyIndexes: file_api_proto_boss_provision_v1_provision_proto_depIdxs,
		MessageInfos:      file_api_proto_boss_provision_v1_provision_proto_msgTypes,
	}.Build()
	File_api_proto_boss_provision_v1_provision_proto = out.File
	file_api_proto_boss_provision_v1_provision_proto_goTypes = nil
	file_api_proto_boss_provision_v1_provision_proto_depIdxs = nil
}
