// geo 集群共享 tailwind 类名:替代原 geo.css(令牌改走全局 shell-* 体系)。
export const CARD = 'rounded-md border border-[var(--shell-card-border)] bg-[var(--shell-card-bg)] shadow-[var(--shell-card-shadow)]'
export const TOOLBAR = 'flex flex-wrap items-center gap-2 p-4'
export const SPACER = 'flex-1'
export const TABLE_WRAP = 'overflow-x-auto px-4 pb-4'
export const FOOTER = 'flex justify-end px-4 py-3 text-xs text-[var(--shell-group-title)]'
export const FORM = 'grid grid-cols-2 gap-3.5 gap-x-4'
export const FIELD = 'flex flex-col gap-1.5'
export const FIELD_FULL = 'col-span-full flex flex-col gap-1.5'
export const LABEL = 'text-xs text-[var(--shell-content-text)]'
export const REQ = 'mr-0.5 text-[var(--color-danger)]'
export const HINT = 'text-[11px] text-[var(--shell-input-placeholder)]'
export const ACT_BTN = 'border-none bg-none px-1 text-[13px] text-[var(--color-text-link)] cursor-pointer hover:text-[var(--color-brand-gold-600)] hover:underline'
export const SEP = 'text-[var(--shell-side-border)]'
export const ADDR_ROW = 'flex items-center gap-2 rounded-sm px-2 py-1.5 text-[13px] hover:bg-[var(--shell-menu-hover-bg)]'
export const ADDR_TOGGLE = 'h-5 w-5 flex-none cursor-pointer rounded border border-[var(--shell-input-border)] bg-none text-center text-[13px] leading-[18px] text-[var(--shell-content-text)] hover:border-[var(--color-text-link)] hover:text-[var(--color-text-link)]'
export const ADDR_NAME = 'min-w-24 text-[var(--shell-content-text)]'
