#!/usr/bin/env bash
# TL1 102 E2E 验收：tl1sim 为测试仿真器，不进生产镜像；验收端使用宿主二进制。
# B 口径：独立订单分别验证 UP 正向、Power-Off 负向、UP 恢复正向。
set -euo pipefail
BASE_URL="${1:-http://192.168.0.102:28080}"; API="$BASE_URL/api/admin/v1"; HOST="${TL1_HOST:-imeepos@192.168.0.102}"
ADMIN_KEY="${ADMIN_API_KEY:-boss_a852c8434c1ae6370e454817dd6e497c}"; USER_KEY="${USER_API_KEY:-boss_100e5216b416080d4b95c7f3d648c6c1}"
STAMP="$(date +%s)"; PREFIX="acc_tl1_$STAMP"; RESOURCE_ID=0; TEMPLATE_ID=0; SIM_PID=0; SIM_RECORD=/tmp/tl1sim-t6.jsonl
sql(){ ssh "$HOST" "docker exec -i boss-infra-postgres-1 psql -q -U boss -d boss -Atc \"$1\""; }
api(){ local m=$1 p=$2 b=${3:-}; if [ -n "$b" ]; then curl -sS -f -X "$m" "$API$p" -H "X-API-Key: $ADMIN_KEY" -H 'Content-Type: application/json' -d "$b"; else curl -sS -f -X "$m" "$API$p" -H "X-API-Key: $ADMIN_KEY"; fi; }
stop_sim(){ ssh "$HOST" "pkill -x tl1sim >/dev/null 2>&1 || true; rm -f /tmp/tl1sim-t6.jsonl /tmp/tl1sim-t6.log"; }
start_sim(){ local state=$1; stop_sim; ssh "$HOST" "nohup /home/imeepos/bin/tl1sim -addr 0.0.0.0:13027 -user admin -pass admin -onu-oper-state $state -record /tmp/tl1sim-t6.jsonl >/tmp/tl1sim-t6.log 2>&1 &"; sleep 1; }
start_t6(){ ssh "$HOST" "docker rm -f boss-provisioner-t6 >/dev/null 2>&1 || true; docker run -d --name boss-provisioner-t6 --network boss-app_default --entrypoint boss-provisioner -e BOSS_PG_DSN='host=192.168.0.102 port=25432 user=boss password=boss dbname=boss sslmode=disable' -e BOSS_PROVISION_DRIVER=tl1 -e BOSS_PROVISION_TL1_ADDR=172.26.0.1:13027 -e BOSS_PROVISION_TL1_USER=admin -e BOSS_PROVISION_TL1_PASS=admin boss/server:tl1-e2e >/dev/null; docker network connect boss-infra_default boss-provisioner-t6"; }
wait_task(){ local id=$1 want=$2 s=; for _ in $(seq 1 40); do s=$(sql "SELECT status FROM provision_tasks WHERE id=$id"|tr -d '[:space:]'); [ "$s" = "$want" ] && return 0; sleep 2; done; echo "FAIL task=$id expected=$want got=$s" >&2; return 1; }
cleanup(){ set +e; echo "==> cleanup $PREFIX"; ssh "$HOST" "docker rm -f boss-provisioner-t6 >/dev/null 2>&1 || true; pkill -x tl1sim >/dev/null 2>&1 || true; rm -f /tmp/tl1sim-t6.jsonl /tmp/tl1sim-t6.log"; sql "BEGIN; CREATE TEMP TABLE ao AS SELECT id FROM orders WHERE order_no LIKE 'ORD-20260902-%' AND id >= (SELECT coalesce(max(id),0)-3 FROM orders); DELETE FROM provision_logs WHERE task_id IN (SELECT id FROM provision_tasks WHERE order_id IN (SELECT id FROM ao)); DELETE FROM provision_tasks WHERE order_id IN (SELECT id FROM ao); DELETE FROM scan_logs WHERE order_id IN (SELECT id FROM ao); DELETE FROM dispatch_tickets WHERE order_id IN (SELECT id FROM ao); DELETE FROM activation_callbacks WHERE order_id IN (SELECT id FROM ao); DELETE FROM order_stages WHERE order_id IN (SELECT id FROM ao); DELETE FROM pon_onu_alloc WHERE olt_resource_id=$RESOURCE_ID; DELETE FROM ports WHERE resource_id=$RESOURCE_ID; DELETE FROM resources WHERE id=$RESOURCE_ID; DELETE FROM provision_templates WHERE id=$TEMPLATE_ID; DELETE FROM orders WHERE id IN (SELECT id FROM ao); COMMIT;" >/dev/null; ssh "$HOST" "docker start boss-provisioner >/dev/null 2>&1 || true; rm -rf /tmp/boss-tl1e2e"; }
trap cleanup EXIT
echo "==> T6 target=$BASE_URL prefix=$PREFIX"; ssh "$HOST" "docker stop boss-provisioner >/dev/null"
RES=$(api POST /provision/resources "{\"code\":\"OLT-$PREFIX\",\"name\":\"TL1 $PREFIX\",\"type\":\"OLT\",\"addressId\":290,\"legalEntityId\":1}"); RESOURCE_ID=$(echo "$RES"|jq -r '.data.id')
for n in 5 6 7; do PORT_JSON=$(api POST /provision/ports "{\"portCode\":\"P-$PREFIX-0$n\",\"resourceId\":$RESOURCE_ID,\"addressId\":290,\"legalEntityId\":1}"); PORT_ID=$(echo "$PORT_JSON"|jq -r .data.portId); [ -n "$PORT_ID" ] && [ "$PORT_ID" != null ] || exit 1; done
TEMPLATE_ID=$(sql "INSERT INTO provision_templates(legal_entity_id,code,name,content,version,status) VALUES(1,'TPL-$PREFIX','TL1 $PREFIX',jsonb_build_object('bandwidth','100M','onuType','Internet','services',jsonb_build_object('internet',jsonb_build_object('svlan',1113,'cvlan',1,'uv',100,'scos',0,'ccos',0),'tr069',jsonb_build_object('cvlan',1000,'uv',1000,'scos',6,'ccos',6))),1,'ENABLED') RETURNING id"|tr -d '[:space:]')
sql "UPDATE resources SET nms_oltid='$PREFIX-OLTID' WHERE id=$RESOURCE_ID;" >/dev/null
run_order(){ local state=$1 label=$2 port_no=$3 order order_no order_id port task loid status; start_sim "$state"; order=$(curl -sS -f -X POST "$BASE_URL/api/user/v1/orders" -H "X-API-Key: $USER_KEY" -H 'Content-Type: application/json' -d '{"productId":"101","addressId":"290","channelId":"102"}'); order_no=$(echo "$order"|jq -r '.data.orderNo'); order_id=$(sql "SELECT id FROM orders WHERE order_no='$order_no'"|tr -d '[:space:]'); api POST "/orders/$order_no/check-resource" >/dev/null; api POST "/orders/$order_no/reserve" >/dev/null; port=$(sql "SELECT id FROM ports WHERE order_id=$order_id LIMIT 1"|tr -d '[:space:]'); sql "UPDATE ports SET resource_id=$RESOURCE_ID,pon_frame=0,pon_slot=7,pon_port=$port_no,onu_no=NULL WHERE id=$port;" >/dev/null; api POST "/orders/$order_no/charge" >/dev/null; sql "UPDATE provision_tasks SET template_id=$TEMPLATE_ID WHERE order_id=$order_id;" >/dev/null; start_t6; task=$(sql "SELECT id FROM provision_tasks WHERE order_id=$order_id AND stage_event='preConfigOLT' ORDER BY id DESC LIMIT 1"|tr -d '[:space:]'); wait_task "$task" DONE; echo "  PASS $label preConfig task=$task order=$order_no"; loid=$(sql "SELECT id FROM lo_accounts WHERE customer_id=(SELECT customer_id FROM orders WHERE id=$order_id) ORDER BY id LIMIT 1"|tr -d '[:space:]'); task=$(sql "INSERT INTO provision_tasks(task_no,order_id,stage_event,lo_account_id,template_id,status) VALUES('T6-$PREFIX-$label',$order_id,'activateUser',$loid,$TEMPLATE_ID,'PENDING') RETURNING id"|tr -d '[:space:]'); if [ "$state" = Power-Off ]; then wait_task "$task" FAILED; else wait_task "$task" DONE; fi; status=$(sql "SELECT status FROM orders WHERE id=$order_id"|tr -d '[:space:]'); if [ "$state" = Power-Off ]; then [ "$status" = INSTALLING ] || { echo "FAIL $label order status=$status" >&2; return 1; }; reason=$(sql "SELECT result FROM provision_logs WHERE task_id=$task ORDER BY id DESC LIMIT 1"|tr -d '[:space:]'); echo "  PASS $label activateUser FAILED order=$order_no task=$task status=$status reason=$reason"; else echo "  PASS $label activateUser DONE order=$order_no task=$task status=$status"; fi; }
run_order UP positive-a 5; run_order Power-Off negative-poweroff 6; run_order UP positive-b 7
REC=$(ssh "$HOST" "cat $SIM_RECORD"); echo "$REC"|grep -q 'ADD-ONU'; echo "$REC"|grep -q 'ADD-PONVLAN'; echo "$REC"|grep -q 'ONUID=LOID-C-00000216'; echo "$REC"|grep -q 'DESC=PRV-'; echo "PASS: TL1 102 E2E 正向/Power-Off 负向/恢复正向证据成立"
