#!/usr/bin/env bash
# TL1 102 E2E：tl1sim 为测试仿真器，不进生产镜像；验收端使用宿主二进制。
# B 口径：三笔隔离订单分别验证 UP 正向、Power-Off 负向、UP 恢复正向。
set -uo pipefail
BASE_URL="${1:-http://192.168.0.102:28080}"; API="$BASE_URL/api/admin/v1"
HOST="${TL1_HOST:-imeepos@192.168.0.102}"; ADMIN_KEY="${ADMIN_API_KEY:-boss_a852c8434c1ae6370e454817dd6e497c}"; USER_KEY="${USER_API_KEY:-boss_100e5216b416080d4b95c7f3d648c6c1}"
STAMP="$(date +%s)"; PREFIX="acc_tl1_$STAMP"; RESOURCE_ID=0; TEMPLATE_ID=0; OLD_STOPPED=0
ORDERS=(); TASKS=(); RECORDS=(/tmp/tl1sim-up-a.jsonl /tmp/tl1sim-off-b.jsonl /tmp/tl1sim-up-c.jsonl); PIDFILE=/tmp/tl1sim-t6.pid
fail(){ echo "FAIL: $*" >&2; exit 1; }
sql(){ local q=$1; ssh "$HOST" "docker exec -i boss-infra-postgres-1 psql -q -v ON_ERROR_STOP=1 -U boss -d boss -Atc \"$q\""; }
api(){ local m=$1 p=$2 b=${3:-} out; if [ -n "$b" ]; then out=$(curl -sS -f -X "$m" "$API$p" -H "X-API-Key: $ADMIN_KEY" -H 'Content-Type: application/json' -d "$b") || fail "api $m $p"; else out=$(curl -sS -f -X "$m" "$API$p" -H "X-API-Key: $ADMIN_KEY") || fail "api $m $p"; fi; echo "$out" | jq -e '.code == 0 or .code == 200' >/dev/null || fail "api $m $p response=$out"; echo "$out"; }
stop_sim(){ ssh "$HOST" "if test -s $PIDFILE; then pid=\$(cat $PIDFILE); kill \$pid >/dev/null 2>&1 || true; rm -f $PIDFILE; fi" || fail 'stop own tl1sim'; }
start_sim(){ local state=$1 record=$2; stop_sim; ssh "$HOST" "test -x /home/imeepos/bin/tl1sim" || fail 'missing /home/imeepos/bin/tl1sim'; ssh "$HOST" "rm -f $record /tmp/tl1sim-t6.log $PIDFILE; nohup /home/imeepos/bin/tl1sim -addr 0.0.0.0:13027 -user admin -pass admin -onu-oper-state $state -record $record >/tmp/tl1sim-t6.log 2>&1 & echo \$! > $PIDFILE" || fail "start sim $state"; sleep 1; ssh "$HOST" "test -s $PIDFILE" || fail 'sim pidfile missing'; }
start_t6(){ ssh "$HOST" "docker rm -f boss-provisioner-t6 >/dev/null 2>&1 || true; docker run -d --name boss-provisioner-t6 --network boss-app_default --entrypoint boss-provisioner -e BOSS_PG_DSN='host=192.168.0.102 port=25432 user=boss password=boss dbname=boss sslmode=disable' -e BOSS_PROVISION_DRIVER=tl1 -e BOSS_PROVISION_TL1_ADDR=172.26.0.1:13027 -e BOSS_PROVISION_TL1_USER=admin -e BOSS_PROVISION_TL1_PASS=admin boss/server:tl1-e2e >/dev/null; docker network connect boss-infra_default boss-provisioner-t6" || fail 'start isolated provisioner'; }
wait_task(){ local id=$1 want=$2 label=$3 s=; for _ in $(seq 1 45); do s=$(sql "SELECT status FROM provision_tasks WHERE id=$id"|tr -d '[:space:]'); [ "$s" = "$want" ] && return 0; sleep 2; done; fail "$label task=$id expected=$want got=$s"; }
cleanup(){ local rc=$?; set +e; echo "==> cleanup prefix=$PREFIX"; stop_sim; ssh "$HOST" "docker rm -f boss-provisioner-t6 >/dev/null 2>&1 || true; docker start boss-provisioner >/dev/null 2>&1 || true"; for id in "${ORDERS[@]}"; do [ -n "$id" ] || continue; sql "DELETE FROM provision_logs WHERE task_id IN (SELECT id FROM provision_tasks WHERE order_id=$id); DELETE FROM provision_tasks WHERE order_id=$id; DELETE FROM scan_logs WHERE order_id=$id; DELETE FROM dispatch_tickets WHERE order_id=$id; DELETE FROM activation_callbacks WHERE order_id=$id; DELETE FROM order_stages WHERE order_id=$id;" >/dev/null; done; [ "$RESOURCE_ID" = 0 ] || sql "DELETE FROM pon_onu_alloc WHERE olt_resource_id=$RESOURCE_ID; DELETE FROM ports WHERE resource_id=$RESOURCE_ID; DELETE FROM resources WHERE id=$RESOURCE_ID;" >/dev/null; [ "$TEMPLATE_ID" = 0 ] || sql "DELETE FROM provision_templates WHERE id=$TEMPLATE_ID;" >/dev/null; for id in "${ORDERS[@]}"; do [ -n "$id" ] && sql "DELETE FROM orders WHERE id=$id;" >/dev/null; done; ssh "$HOST" "test -x /home/imeepos/bin/tl1sim && rm -f /tmp/tl1sim-t6.log ${RECORDS[*]} $PIDFILE" >/dev/null 2>&1 || true; if [ "$OLD_STOPPED" = 1 ]; then ssh "$HOST" "docker start boss-provisioner >/dev/null 2>&1 || true"; fi; if [ "$(ssh "$HOST" "docker inspect -f '{{.State.Running}}' boss-provisioner 2>/dev/null")" != "true" ]; then echo 'WARN: boss-provisioner not running after cleanup' >&2; fi; exit $rc; }
trap cleanup EXIT
echo "==> T6 target=$BASE_URL prefix=$PREFIX"
PENDING=$(sql "SELECT count(*) FROM provision_tasks WHERE status IN ('PENDING','DOING')"|tr -d '[:space:]'); [ "$PENDING" = 0 ] || fail "queue not empty before stop: $PENDING"
ssh "$HOST" "docker stop boss-provisioner >/dev/null" || fail 'stop original provisioner'; OLD_STOPPED=1
RES=$(api POST /provision/resources "{\"code\":\"OLT-$PREFIX\",\"name\":\"TL1 $PREFIX\",\"type\":\"OLT\",\"addressId\":290,\"legalEntityId\":1}"); RESOURCE_ID=$(echo "$RES"|jq -r '.data.id'); [[ "$RESOURCE_ID" =~ ^[0-9]+$ ]] && [ "$RESOURCE_ID" -gt 0 ] || fail "resource id response=$RES"
for n in 5 6 7; do P=$(api POST /provision/ports "{\"portCode\":\"P-$PREFIX-0$n\",\"resourceId\":$RESOURCE_ID,\"addressId\":290,\"legalEntityId\":1}"); PID=$(echo "$P"|jq -r '.data.portId'); [[ "$PID" =~ ^[0-9]+$ ]] || fail "port id response=$P"; done
TEMPLATE_ID=$(sql "INSERT INTO provision_templates(legal_entity_id,code,name,content,version,status) VALUES(1,'TPL-$PREFIX','TL1 $PREFIX',jsonb_build_object('bandwidth','100M','onuType','Internet','services',jsonb_build_object('internet',jsonb_build_object('svlan',1113,'cvlan',1,'uv',100,'scos',0,'ccos',0),'tr069',jsonb_build_object('cvlan',1000,'uv',1000,'scos',6,'ccos',6))),1,'ENABLED') RETURNING id"|tr -d '[:space:]'); [[ "$TEMPLATE_ID" =~ ^[0-9]+$ ]] || fail 'template insert failed'
sql "UPDATE resources SET nms_oltid='$PREFIX-OLTID' WHERE id=$RESOURCE_ID;" >/dev/null
run_order(){ local state=$1 label=$2 port_no=$3 order no oid port task loid status record=$4; start_sim "$state" "$record"; order=$(curl -sS -f -X POST "$BASE_URL/api/user/v1/orders" -H "X-API-Key: $USER_KEY" -H 'Content-Type: application/json' -d '{"productId":"101","addressId":"290","channelId":"102"}') || fail "create $label order"; no=$(echo "$order"|jq -r '.data.orderNo'); oid=$(sql "SELECT id FROM orders WHERE order_no='$no'"|tr -d '[:space:]'); [[ "$oid" =~ ^[0-9]+$ ]] || fail "order id $label"; ORDERS+=("$oid"); api POST "/orders/$no/check-resource" >/dev/null; api POST "/orders/$no/reserve" >/dev/null; port=$(sql "SELECT id FROM ports WHERE order_id=$oid LIMIT 1"|tr -d '[:space:]'); [[ "$port" =~ ^[0-9]+$ ]] || fail "reserved port $label"; sql "UPDATE ports SET resource_id=$RESOURCE_ID,pon_frame=0,pon_slot=7,pon_port=$port_no,onu_no=NULL WHERE id=$port;" >/dev/null; api POST "/orders/$no/charge" >/dev/null; sql "UPDATE provision_tasks SET template_id=$TEMPLATE_ID WHERE order_id=$oid;" >/dev/null; start_t6; task=$(sql "SELECT id FROM provision_tasks WHERE order_id=$oid AND stage_event='preConfigOLT' ORDER BY id DESC LIMIT 1"|tr -d '[:space:]'); wait_task "$task" DONE "$label preConfig"; echo "  PASS $label preConfig order=$no task=$task"; loid=$(sql "SELECT id FROM lo_accounts WHERE customer_id=(SELECT customer_id FROM orders WHERE id=$oid) ORDER BY id LIMIT 1"|tr -d '[:space:]'); task=$(sql "INSERT INTO provision_tasks(task_no,order_id,stage_event,lo_account_id,template_id,status) VALUES('T6-$label',$oid,'activateUser',$loid,$TEMPLATE_ID,'PENDING') RETURNING id"|tr -d '[:space:]'); if [ "$state" = Power-Off ]; then wait_task "$task" FAILED "$label activate"; reason=$(sql "SELECT result FROM provision_logs WHERE task_id=$task ORDER BY id DESC LIMIT 1"); status=$(sql "SELECT status FROM orders WHERE id=$oid"|tr -d '[:space:]'); [ "$status" = INSTALLING ] || fail "$label order moved to $status"; echo "  PASS $label activate FAILED order=$no task=$task status=$status result=$reason"; else wait_task "$task" DONE "$label activate"; status=$(sql "SELECT status FROM orders WHERE id=$oid"|tr -d '[:space:]'); echo "  PASS $label activate DONE order=$no task=$task status=$status"; fi; echo "  RECORD $label: $(ssh "$HOST" "grep -E 'LOGIN|ADD-ONU|ADD-PONVLAN|LST-ONUSTATE' $record | tail -8")"; }
run_order UP positive-a 5 "${RECORDS[0]}"; run_order Power-Off negative-poweroff 6 "${RECORDS[1]}"; run_order UP positive-c 7 "${RECORDS[2]}"
echo "PASS: TL1 102 E2E 三订单正向/Power-Off负向/恢复正向通过"
