// boss/aaa/v1 —— AAA 联动契约(billing→aaa,阶段7/W6)。
// 语义:停复机即时生效、授权查询(LOID/QoS)、实时话单入账。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: api/proto/boss/aaa/v1/aaa.proto

package aaav1

import (
	v1 "github.com/ymm-001/boss/api/proto/boss/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SuspendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoAccountId   int64                  `protobuf:"varint,1,opt,name=lo_account_id,json=loAccountId,proto3" json:"lo_account_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // ARREARS / MANUAL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendRequest) Reset() {
	*x = SuspendRequest{}
	mi := &file_api_proto_boss_aaa_v1_aaa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendRequest) ProtoMessage() {}

func (x *SuspendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_aaa_v1_aaa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendRequest.ProtoReflect.Descriptor instead.
func (*SuspendRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_aaa_v1_aaa_proto_rawDescGZIP(), []int{0}
}

func (x *SuspendRequest) GetLoAccountId() int64 {
	if x != nil {
		return x.LoAccountId
	}
	return 0
}

func (x *SuspendRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoAccountId   int64                  `protobuf:"varint,1,opt,name=lo_account_id,json=loAccountId,proto3" json:"lo_account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_api_proto_boss_aaa_v1_aaa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_aaa_v1_aaa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_aaa_v1_aaa_proto_rawDescGZIP(), []int{1}
}

func (x *ResumeRequest) GetLoAccountId() int64 {
	if x != nil {
		return x.LoAccountId
	}
	return 0
}

type OpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          v1.Code                `protobuf:"varint,1,opt,name=code,proto3,enum=boss.common.v1.Code" json:"code,omitempty"`
	Effective     bool                   `protobuf:"varint,2,opt,name=effective,proto3" json:"effective,omitempty"` // 是否已即时生效
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpResponse) Reset() {
	*x = OpResponse{}
	mi := &file_api_proto_boss_aaa_v1_aaa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpResponse) ProtoMessage() {}

func (x *OpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_aaa_v1_aaa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpResponse.ProtoReflect.Descriptor instead.
func (*OpResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_aaa_v1_aaa_proto_rawDescGZIP(), []int{2}
}

func (x *OpResponse) GetCode() v1.Code {
	if x != nil {
		return x.Code
	}
	return v1.Code(0)
}

func (x *OpResponse) GetEffective() bool {
	if x != nil {
		return x.Effective
	}
	return false
}

type GetAuthorizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loid          string                 `protobuf:"bytes,1,opt,name=loid,proto3" json:"loid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorizationRequest) Reset() {
	*x = GetAuthorizationRequest{}
	mi := &file_api_proto_boss_aaa_v1_aaa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationRequest) ProtoMessage() {}

func (x *GetAuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_aaa_v1_aaa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_aaa_v1_aaa_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuthorizationRequest) GetLoid() string {
	if x != nil {
		return x.Loid
	}
	return ""
}

type Authorization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          v1.Code                `protobuf:"varint,1,opt,name=code,proto3,enum=boss.common.v1.Code" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`       // ACTIVE / SUSPENDED
	Bandwidth     string                 `protobuf:"bytes,3,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"` // 如 300M/150M
	QosTemplate   string                 `protobuf:"bytes,4,opt,name=qos_template,json=qosTemplate,proto3" json:"qos_template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authorization) Reset() {
	*x = Authorization{}
	mi := &file_api_proto_boss_aaa_v1_aaa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authorization) ProtoMessage() {}

func (x *Authorization) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_aaa_v1_aaa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authorization.ProtoReflect.Descriptor instead.
func (*Authorization) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_aaa_v1_aaa_proto_rawDescGZIP(), []int{4}
}

func (x *Authorization) GetCode() v1.Code {
	if x != nil {
		return x.Code
	}
	return v1.Code(0)
}

func (x *Authorization) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Authorization) GetBandwidth() string {
	if x != nil {
		return x.Bandwidth
	}
	return ""
}

func (x *Authorization) GetQosTemplate() string {
	if x != nil {
		return x.QosTemplate
	}
	return ""
}

type CDR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loid          string                 `protobuf:"bytes,1,opt,name=loid,proto3" json:"loid,omitempty"`
	LoAccountId   int64                  `protobuf:"varint,2,opt,name=lo_account_id,json=loAccountId,proto3" json:"lo_account_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // Start / Interim-Update / Stop
	InputOctets   uint64                 `protobuf:"varint,5,opt,name=input_octets,json=inputOctets,proto3" json:"input_octets,omitempty"`
	OutputOctets  uint64                 `protobuf:"varint,6,opt,name=output_octets,json=outputOctets,proto3" json:"output_octets,omitempty"`
	StartedAt     int64                  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`    // unix 秒
	FinishedAt    int64                  `protobuf:"varint,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"` // unix 秒,Stop 时有效
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CDR) Reset() {
	*x = CDR{}
	mi := &file_api_proto_boss_aaa_v1_aaa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CDR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDR) ProtoMessage() {}

func (x *CDR) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_aaa_v1_aaa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDR.ProtoReflect.Descriptor instead.
func (*CDR) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_aaa_v1_aaa_proto_rawDescGZIP(), []int{5}
}

func (x *CDR) GetLoid() string {
	if x != nil {
		return x.Loid
	}
	return ""
}

func (x *CDR) GetLoAccountId() int64 {
	if x != nil {
		return x.LoAccountId
	}
	return 0
}

func (x *CDR) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CDR) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *CDR) GetInputOctets() uint64 {
	if x != nil {
		return x.InputOctets
	}
	return 0
}

func (x *CDR) GetOutputOctets() uint64 {
	if x != nil {
		return x.OutputOctets
	}
	return 0
}

func (x *CDR) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *CDR) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

var File_api_proto_boss_aaa_v1_aaa_proto protoreflect.FileDescriptor

const file_api_proto_boss_aaa_v1_aaa_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/boss/aaa/v1/aaa.proto\x12\vboss.aaa.v1\x1a%api/proto/boss/common/v1/common.proto\"L\n" +
	"\x0eSuspendRequest\x12\"\n" +
	"\rlo_account_id\x18\x01 \x01(\x03R\vloAccountId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"3\n" +
	"\rResumeRequest\x12\"\n" +
	"\rlo_account_id\x18\x01 \x01(\x03R\vloAccountId\"T\n" +
	"\n" +
	"OpResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.boss.common.v1.CodeR\x04code\x12\x1c\n" +
	"\teffective\x18\x02 \x01(\bR\teffective\"-\n" +
	"\x17GetAuthorizationRequest\x12\x12\n" +
	"\x04loid\x18\x01 \x01(\tR\x04loid\"\x92\x01\n" +
	"\rAuthorization\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.boss.common.v1.CodeR\x04code\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\tbandwidth\x18\x03 \x01(\tR\tbandwidth\x12!\n" +
	"\fqos_template\x18\x04 \x01(\tR\vqosTemplate\"\x83\x02\n" +
	"\x03CDR\x12\x12\n" +
	"\x04loid\x18\x01 \x01(\tR\x04loid\x12\"\n" +
	"\rlo_account_id\x18\x02 \x01(\x03R\vloAccountId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12!\n" +
	"\finput_octets\x18\x05 \x01(\x04R\vinputOctets\x12#\n" +
	"\routput_octets\x18\x06 \x01(\x04R\foutputOctets\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\b \x01(\x03R\n" +
	"finishedAt2\x98\x02\n" +
	"\n" +
	"AaaService\x12?\n" +
	"\aSuspend\x12\x1b.boss.aaa.v1.SuspendRequest\x1a\x17.boss.aaa.v1.OpResponse\x12=\n" +
	"\x06Resume\x12\x1a.boss.aaa.v1.ResumeRequest\x1a\x17.boss.aaa.v1.OpResponse\x12T\n" +
	"\x10GetAuthorization\x12$.boss.aaa.v1.GetAuthorizationRequest\x1a\x1a.boss.aaa.v1.Authorization\x124\n" +
	"\aEmitCDR\x12\x10.boss.aaa.v1.CDR\x1a\x17.boss.aaa.v1.OpResponseB5Z3github.com/ymm-001/boss/api/proto/boss/aaa/v1;aaav1b\x06proto3"

var (
	file_api_proto_boss_aaa_v1_aaa_proto_rawDescOnce sync.Once
	file_api_proto_boss_aaa_v1_aaa_proto_rawDescData []byte
)

func file_api_proto_boss_aaa_v1_aaa_proto_rawDescGZIP() []byte {
	file_api_proto_boss_aaa_v1_aaa_proto_rawDescOnce.Do(func() {
		file_api_proto_boss_aaa_v1_aaa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_boss_aaa_v1_aaa_proto_rawDesc), len(file_api_proto_boss_aaa_v1_aaa_proto_rawDesc)))
	})
	return file_api_proto_boss_aaa_v1_aaa_proto_rawDescData
}

var file_api_proto_boss_aaa_v1_aaa_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_boss_aaa_v1_aaa_proto_goTypes = []any{
	(*SuspendRequest)(nil),          // 0: boss.aaa.v1.SuspendRequest
	(*ResumeRequest)(nil),           // 1: boss.aaa.v1.ResumeRequest
	(*OpResponse)(nil),              // 2: boss.aaa.v1.OpResponse
	(*GetAuthorizationRequest)(nil), // 3: boss.aaa.v1.GetAuthorizationRequest
	(*Authorization)(nil),           // 4: boss.aaa.v1.Authorization
	(*CDR)(nil),                     // 5: boss.aaa.v1.CDR
	(v1.Code)(0),                    // 6: boss.common.v1.Code
}
var file_api_proto_boss_aaa_v1_aaa_proto_depIdxs = []int32{
	6, // 0: boss.aaa.v1.OpResponse.code:type_name -> boss.common.v1.Code
	6, // 1: boss.aaa.v1.Authorization.code:type_name -> boss.common.v1.Code
	0, // 2: boss.aaa.v1.AaaService.Suspend:input_type -> boss.aaa.v1.SuspendRequest
	1, // 3: boss.aaa.v1.AaaService.Resume:input_type -> boss.aaa.v1.ResumeRequest
	3, // 4: boss.aaa.v1.AaaService.GetAuthorization:input_type -> boss.aaa.v1.GetAuthorizationRequest
	5, // 5: boss.aaa.v1.AaaService.EmitCDR:input_type -> boss.aaa.v1.CDR
	2, // 6: boss.aaa.v1.AaaService.Suspend:output_type -> boss.aaa.v1.OpResponse
	2, // 7: boss.aaa.v1.AaaService.Resume:output_type -> boss.aaa.v1.OpResponse
	4, // 8: boss.aaa.v1.AaaService.GetAuthorization:output_type -> boss.aaa.v1.Authorization
	2, // 9: boss.aaa.v1.AaaService.EmitCDR:output_type -> boss.aaa.v1.OpResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_boss_aaa_v1_aaa_proto_init() }
func file_api_proto_boss_aaa_v1_aaa_proto_init() {
	if File_api_proto_boss_aaa_v1_aaa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_boss_aaa_v1_aaa_proto_rawDesc), len(file_api_proto_boss_aaa_v1_aaa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_boss_aaa_v1_aaa_proto_goTypes,
		DependencyIndexes: file_api_proto_boss_aaa_v1_aaa_proto_depIdxs,
		MessageInfos:      file_api_proto_boss_aaa_v1_aaa_proto_msgTypes,
	}.Build()
	File_api_proto_boss_aaa_v1_aaa_proto = out.File
	file_api_proto_boss_aaa_v1_aaa_proto_goTypes = nil
	file_api_proto_boss_aaa_v1_aaa_proto_depIdxs = nil
}
