// boss/aaa/v1 —— AAA 联动契约(billing→aaa,阶段7/W6)。
// 语义:停复机即时生效、授权查询(LOID/QoS)、实时话单入账。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/boss/aaa/v1/aaa.proto

package aaav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AaaService_Suspend_FullMethodName          = "/boss.aaa.v1.AaaService/Suspend"
	AaaService_Resume_FullMethodName           = "/boss.aaa.v1.AaaService/Resume"
	AaaService_GetAuthorization_FullMethodName = "/boss.aaa.v1.AaaService/GetAuthorization"
	AaaService_EmitCDR_FullMethodName          = "/boss.aaa.v1.AaaService/EmitCDR"
)

// AaaServiceClient is the client API for AaaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AaaService AAA 联动服务。
type AaaServiceClient interface {
	// Suspend 停机(欠费):在线会话下线,拒绝后续认证。
	Suspend(ctx context.Context, in *SuspendRequest, opts ...grpc.CallOption) (*OpResponse, error)
	// Resume 复机(缴费):恢复认证授权。
	Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*OpResponse, error)
	// GetAuthorization 授权查询(LOID → 带宽/QoS/状态)。
	GetAuthorization(ctx context.Context, in *GetAuthorizationRequest, opts ...grpc.CallOption) (*Authorization, error)
	// EmitCDR 实时话单入账(RADIUS Acct → Kafka → billing 的服务内直连形态)。
	EmitCDR(ctx context.Context, in *CDR, opts ...grpc.CallOption) (*OpResponse, error)
}

type aaaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAaaServiceClient(cc grpc.ClientConnInterface) AaaServiceClient {
	return &aaaServiceClient{cc}
}

func (c *aaaServiceClient) Suspend(ctx context.Context, in *SuspendRequest, opts ...grpc.CallOption) (*OpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResponse)
	err := c.cc.Invoke(ctx, AaaService_Suspend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aaaServiceClient) Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*OpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResponse)
	err := c.cc.Invoke(ctx, AaaService_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aaaServiceClient) GetAuthorization(ctx context.Context, in *GetAuthorizationRequest, opts ...grpc.CallOption) (*Authorization, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Authorization)
	err := c.cc.Invoke(ctx, AaaService_GetAuthorization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aaaServiceClient) EmitCDR(ctx context.Context, in *CDR, opts ...grpc.CallOption) (*OpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResponse)
	err := c.cc.Invoke(ctx, AaaService_EmitCDR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AaaServiceServer is the server API for AaaService service.
// All implementations must embed UnimplementedAaaServiceServer
// for forward compatibility.
//
// AaaService AAA 联动服务。
type AaaServiceServer interface {
	// Suspend 停机(欠费):在线会话下线,拒绝后续认证。
	Suspend(context.Context, *SuspendRequest) (*OpResponse, error)
	// Resume 复机(缴费):恢复认证授权。
	Resume(context.Context, *ResumeRequest) (*OpResponse, error)
	// GetAuthorization 授权查询(LOID → 带宽/QoS/状态)。
	GetAuthorization(context.Context, *GetAuthorizationRequest) (*Authorization, error)
	// EmitCDR 实时话单入账(RADIUS Acct → Kafka → billing 的服务内直连形态)。
	EmitCDR(context.Context, *CDR) (*OpResponse, error)
	mustEmbedUnimplementedAaaServiceServer()
}

// UnimplementedAaaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAaaServiceServer struct{}

func (UnimplementedAaaServiceServer) Suspend(context.Context, *SuspendRequest) (*OpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Suspend not implemented")
}
func (UnimplementedAaaServiceServer) Resume(context.Context, *ResumeRequest) (*OpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedAaaServiceServer) GetAuthorization(context.Context, *GetAuthorizationRequest) (*Authorization, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthorization not implemented")
}
func (UnimplementedAaaServiceServer) EmitCDR(context.Context, *CDR) (*OpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmitCDR not implemented")
}
func (UnimplementedAaaServiceServer) mustEmbedUnimplementedAaaServiceServer() {}
func (UnimplementedAaaServiceServer) testEmbeddedByValue()                    {}

// UnsafeAaaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AaaServiceServer will
// result in compilation errors.
type UnsafeAaaServiceServer interface {
	mustEmbedUnimplementedAaaServiceServer()
}

func RegisterAaaServiceServer(s grpc.ServiceRegistrar, srv AaaServiceServer) {
	// If the following call panics, it indicates UnimplementedAaaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AaaService_ServiceDesc, srv)
}

func _AaaService_Suspend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AaaServiceServer).Suspend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AaaService_Suspend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AaaServiceServer).Suspend(ctx, req.(*SuspendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AaaService_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AaaServiceServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AaaService_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AaaServiceServer).Resume(ctx, req.(*ResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AaaService_GetAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AaaServiceServer).GetAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AaaService_GetAuthorization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AaaServiceServer).GetAuthorization(ctx, req.(*GetAuthorizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AaaService_EmitCDR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CDR)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AaaServiceServer).EmitCDR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AaaService_EmitCDR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AaaServiceServer).EmitCDR(ctx, req.(*CDR))
	}
	return interceptor(ctx, in, info, handler)
}

// AaaService_ServiceDesc is the grpc.ServiceDesc for AaaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AaaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "boss.aaa.v1.AaaService",
	HandlerType: (*AaaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Suspend",
			Handler:    _AaaService_Suspend_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _AaaService_Resume_Handler,
		},
		{
			MethodName: "GetAuthorization",
			Handler:    _AaaService_GetAuthorization_Handler,
		},
		{
			MethodName: "EmitCDR",
			Handler:    _AaaService_EmitCDR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/boss/aaa/v1/aaa.proto",
}
