// boss/quadlink/v1 —— 四码合一服务契约(师傅端→服务端,阶段6/W5)。
// 语义:扫码绑定校验(不一致拒)、拆机必扫码、四码反查、对账。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: api/proto/boss/quadlink/v1/quadlink.proto

package quadlinkv1

import (
	v1 "github.com/ymm-001/boss/api/proto/boss/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanBindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketNo      string                 `protobuf:"bytes,1,opt,name=ticket_no,json=ticketNo,proto3" json:"ticket_no,omitempty"`  // 派单工单号(→ orderID)
	Epc           string                 `protobuf:"bytes,2,opt,name=epc,proto3" json:"epc,omitempty"`                            // 实物电子标签 EPC
	WorkerId      int64                  `protobuf:"varint,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // 装维师傅
	WorkerName    string                 `protobuf:"bytes,4,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	Offline       bool                   `protobuf:"varint,5,opt,name=offline,proto3" json:"offline,omitempty"` // 弱网离线缓存补传
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanBindRequest) Reset() {
	*x = ScanBindRequest{}
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanBindRequest) ProtoMessage() {}

func (x *ScanBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanBindRequest.ProtoReflect.Descriptor instead.
func (*ScanBindRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_quadlink_v1_quadlink_proto_rawDescGZIP(), []int{0}
}

func (x *ScanBindRequest) GetTicketNo() string {
	if x != nil {
		return x.TicketNo
	}
	return ""
}

func (x *ScanBindRequest) GetEpc() string {
	if x != nil {
		return x.Epc
	}
	return ""
}

func (x *ScanBindRequest) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *ScanBindRequest) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *ScanBindRequest) GetOffline() bool {
	if x != nil {
		return x.Offline
	}
	return false
}

type ScanBindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          v1.Code                `protobuf:"varint,1,opt,name=code,proto3,enum=boss.common.v1.Code" json:"code,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`                                     // MATCH / MISMATCH / OFFLINE_CACHED
	StageAdvanced bool                   `protobuf:"varint,3,opt,name=stage_advanced,json=stageAdvanced,proto3" json:"stage_advanced,omitempty"` // MATCH 时是否推进环节9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanBindResponse) Reset() {
	*x = ScanBindResponse{}
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanBindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanBindResponse) ProtoMessage() {}

func (x *ScanBindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanBindResponse.ProtoReflect.Descriptor instead.
func (*ScanBindResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_quadlink_v1_quadlink_proto_rawDescGZIP(), []int{1}
}

func (x *ScanBindResponse) GetCode() v1.Code {
	if x != nil {
		return x.Code
	}
	return v1.Code(0)
}

func (x *ScanBindResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ScanBindResponse) GetStageAdvanced() bool {
	if x != nil {
		return x.StageAdvanced
	}
	return false
}

type DismantleScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketNo      string                 `protobuf:"bytes,1,opt,name=ticket_no,json=ticketNo,proto3" json:"ticket_no,omitempty"`
	Epc           string                 `protobuf:"bytes,2,opt,name=epc,proto3" json:"epc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismantleScanRequest) Reset() {
	*x = DismantleScanRequest{}
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismantleScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismantleScanRequest) ProtoMessage() {}

func (x *DismantleScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismantleScanRequest.ProtoReflect.Descriptor instead.
func (*DismantleScanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_quadlink_v1_quadlink_proto_rawDescGZIP(), []int{2}
}

func (x *DismantleScanRequest) GetTicketNo() string {
	if x != nil {
		return x.TicketNo
	}
	return ""
}

func (x *DismantleScanRequest) GetEpc() string {
	if x != nil {
		return x.Epc
	}
	return ""
}

type DismantleScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          v1.Code                `protobuf:"varint,1,opt,name=code,proto3,enum=boss.common.v1.Code" json:"code,omitempty"`
	Unlinked      bool                   `protobuf:"varint,2,opt,name=unlinked,proto3" json:"unlinked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismantleScanResponse) Reset() {
	*x = DismantleScanResponse{}
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismantleScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismantleScanResponse) ProtoMessage() {}

func (x *DismantleScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismantleScanResponse.ProtoReflect.Descriptor instead.
func (*DismantleScanResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_quadlink_v1_quadlink_proto_rawDescGZIP(), []int{3}
}

func (x *DismantleScanResponse) GetCode() v1.Code {
	if x != nil {
		return x.Code
	}
	return v1.Code(0)
}

func (x *DismantleScanResponse) GetUnlinked() bool {
	if x != nil {
		return x.Unlinked
	}
	return false
}

type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Key:
	//
	//	*QueryRequest_AssetId
	//	*QueryRequest_CustomerId
	//	*QueryRequest_PortId
	//	*QueryRequest_AddressId
	Key           isQueryRequest_Key `protobuf_oneof:"key"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_quadlink_v1_quadlink_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRequest) GetKey() isQueryRequest_Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *QueryRequest) GetAssetId() int64 {
	if x != nil {
		if x, ok := x.Key.(*QueryRequest_AssetId); ok {
			return x.AssetId
		}
	}
	return 0
}

func (x *QueryRequest) GetCustomerId() int64 {
	if x != nil {
		if x, ok := x.Key.(*QueryRequest_CustomerId); ok {
			return x.CustomerId
		}
	}
	return 0
}

func (x *QueryRequest) GetPortId() int64 {
	if x != nil {
		if x, ok := x.Key.(*QueryRequest_PortId); ok {
			return x.PortId
		}
	}
	return 0
}

func (x *QueryRequest) GetAddressId() int64 {
	if x != nil {
		if x, ok := x.Key.(*QueryRequest_AddressId); ok {
			return x.AddressId
		}
	}
	return 0
}

type isQueryRequest_Key interface {
	isQueryRequest_Key()
}

type QueryRequest_AssetId struct {
	AssetId int64 `protobuf:"varint,1,opt,name=asset_id,json=assetId,proto3,oneof"`
}

type QueryRequest_CustomerId struct {
	CustomerId int64 `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3,oneof"`
}

type QueryRequest_PortId struct {
	PortId int64 `protobuf:"varint,3,opt,name=port_id,json=portId,proto3,oneof"`
}

type QueryRequest_AddressId struct {
	AddressId int64 `protobuf:"varint,4,opt,name=address_id,json=addressId,proto3,oneof"`
}

func (*QueryRequest_AssetId) isQueryRequest_Key() {}

func (*QueryRequest_CustomerId) isQueryRequest_Key() {}

func (*QueryRequest_PortId) isQueryRequest_Key() {}

func (*QueryRequest_AddressId) isQueryRequest_Key() {}

type QuadLink struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AssetId         int64                  `protobuf:"varint,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	CustomerId      int64                  `protobuf:"varint,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PortId          int64                  `protobuf:"varint,4,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	AddressId       int64                  `protobuf:"varint,5,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	LegalEntityId   int64                  `protobuf:"varint,6,opt,name=legal_entity_id,json=legalEntityId,proto3" json:"legal_entity_id,omitempty"`
	LegalEntityName string                 `protobuf:"bytes,7,opt,name=legal_entity_name,json=legalEntityName,proto3" json:"legal_entity_name,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // LINKED / CONFLICT / UNLINKED
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QuadLink) Reset() {
	*x = QuadLink{}
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuadLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuadLink) ProtoMessage() {}

func (x *QuadLink) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuadLink.ProtoReflect.Descriptor instead.
func (*QuadLink) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_quadlink_v1_quadlink_proto_rawDescGZIP(), []int{5}
}

func (x *QuadLink) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuadLink) GetAssetId() int64 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

func (x *QuadLink) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *QuadLink) GetPortId() int64 {
	if x != nil {
		return x.PortId
	}
	return 0
}

func (x *QuadLink) GetAddressId() int64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *QuadLink) GetLegalEntityId() int64 {
	if x != nil {
		return x.LegalEntityId
	}
	return 0
}

func (x *QuadLink) GetLegalEntityName() string {
	if x != nil {
		return x.LegalEntityName
	}
	return ""
}

func (x *QuadLink) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReconcileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileRequest) Reset() {
	*x = ReconcileRequest{}
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRequest) ProtoMessage() {}

func (x *ReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRequest.ProtoReflect.Descriptor instead.
func (*ReconcileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_quadlink_v1_quadlink_proto_rawDescGZIP(), []int{6}
}

type ReconcileReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Linked        int32                  `protobuf:"varint,2,opt,name=linked,proto3" json:"linked,omitempty"`
	Conflict      int32                  `protobuf:"varint,3,opt,name=conflict,proto3" json:"conflict,omitempty"`
	Unlinked      int32                  `protobuf:"varint,4,opt,name=unlinked,proto3" json:"unlinked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileReport) Reset() {
	*x = ReconcileReport{}
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileReport) ProtoMessage() {}

func (x *ReconcileReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileReport.ProtoReflect.Descriptor instead.
func (*ReconcileReport) Descriptor() ([]byte, []int) {
	return file_api_proto_boss_quadlink_v1_quadlink_proto_rawDescGZIP(), []int{7}
}

func (x *ReconcileReport) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ReconcileReport) GetLinked() int32 {
	if x != nil {
		return x.Linked
	}
	return 0
}

func (x *ReconcileReport) GetConflict() int32 {
	if x != nil {
		return x.Conflict
	}
	return 0
}

func (x *ReconcileReport) GetUnlinked() int32 {
	if x != nil {
		return x.Unlinked
	}
	return 0
}

var File_api_proto_boss_quadlink_v1_quadlink_proto protoreflect.FileDescriptor

const file_api_proto_boss_quadlink_v1_quadlink_proto_rawDesc = "" +
	"\n" +
	")api/proto/boss/quadlink/v1/quadlink.proto\x12\x10boss.quadlink.v1\x1a%api/proto/boss/common/v1/common.proto\"\x98\x01\n" +
	"\x0fScanBindRequest\x12\x1b\n" +
	"\tticket_no\x18\x01 \x01(\tR\bticketNo\x12\x10\n" +
	"\x03epc\x18\x02 \x01(\tR\x03epc\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\x03R\bworkerId\x12\x1f\n" +
	"\vworker_name\x18\x04 \x01(\tR\n" +
	"workerName\x12\x18\n" +
	"\aoffline\x18\x05 \x01(\bR\aoffline\"{\n" +
	"\x10ScanBindResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.boss.common.v1.CodeR\x04code\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12%\n" +
	"\x0estage_advanced\x18\x03 \x01(\bR\rstageAdvanced\"E\n" +
	"\x14DismantleScanRequest\x12\x1b\n" +
	"\tticket_no\x18\x01 \x01(\tR\bticketNo\x12\x10\n" +
	"\x03epc\x18\x02 \x01(\tR\x03epc\"]\n" +
	"\x15DismantleScanResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.boss.common.v1.CodeR\x04code\x12\x1a\n" +
	"\bunlinked\x18\x02 \x01(\bR\bunlinked\"\x91\x01\n" +
	"\fQueryRequest\x12\x1b\n" +
	"\basset_id\x18\x01 \x01(\x03H\x00R\aassetId\x12!\n" +
	"\vcustomer_id\x18\x02 \x01(\x03H\x00R\n" +
	"customerId\x12\x19\n" +
	"\aport_id\x18\x03 \x01(\x03H\x00R\x06portId\x12\x1f\n" +
	"\n" +
	"address_id\x18\x04 \x01(\x03H\x00R\taddressIdB\x05\n" +
	"\x03key\"\xfa\x01\n" +
	"\bQuadLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\x03R\aassetId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\x03R\n" +
	"customerId\x12\x17\n" +
	"\aport_id\x18\x04 \x01(\x03R\x06portId\x12\x1d\n" +
	"\n" +
	"address_id\x18\x05 \x01(\x03R\taddressId\x12&\n" +
	"\x0flegal_entity_id\x18\x06 \x01(\x03R\rlegalEntityId\x12*\n" +
	"\x11legal_entity_name\x18\a \x01(\tR\x0flegalEntityName\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"\x12\n" +
	"\x10ReconcileRequest\"w\n" +
	"\x0fReconcileReport\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x16\n" +
	"\x06linked\x18\x02 \x01(\x05R\x06linked\x12\x1a\n" +
	"\bconflict\x18\x03 \x01(\x05R\bconflict\x12\x1a\n" +
	"\bunlinked\x18\x04 \x01(\x05R\bunlinked2\xdf\x02\n" +
	"\x0fQuadLinkService\x12Q\n" +
	"\bScanBind\x12!.boss.quadlink.v1.ScanBindRequest\x1a\".boss.quadlink.v1.ScanBindResponse\x12`\n" +
	"\rDismantleScan\x12&.boss.quadlink.v1.DismantleScanRequest\x1a'.boss.quadlink.v1.DismantleScanResponse\x12C\n" +
	"\x05Query\x12\x1e.boss.quadlink.v1.QueryRequest\x1a\x1a.boss.quadlink.v1.QuadLink\x12R\n" +
	"\tReconcile\x12\".boss.quadlink.v1.ReconcileRequest\x1a!.boss.quadlink.v1.ReconcileReportB?Z=github.com/ymm-001/boss/api/proto/boss/quadlink/v1;quadlinkv1b\x06proto3"

var (
	file_api_proto_boss_quadlink_v1_quadlink_proto_rawDescOnce sync.Once
	file_api_proto_boss_quadlink_v1_quadlink_proto_rawDescData []byte
)

func file_api_proto_boss_quadlink_v1_quadlink_proto_rawDescGZIP() []byte {
	file_api_proto_boss_quadlink_v1_quadlink_proto_rawDescOnce.Do(func() {
		file_api_proto_boss_quadlink_v1_quadlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_boss_quadlink_v1_quadlink_proto_rawDesc), len(file_api_proto_boss_quadlink_v1_quadlink_proto_rawDesc)))
	})
	return file_api_proto_boss_quadlink_v1_quadlink_proto_rawDescData
}

var file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_boss_quadlink_v1_quadlink_proto_goTypes = []any{
	(*ScanBindRequest)(nil),       // 0: boss.quadlink.v1.ScanBindRequest
	(*ScanBindResponse)(nil),      // 1: boss.quadlink.v1.ScanBindResponse
	(*DismantleScanRequest)(nil),  // 2: boss.quadlink.v1.DismantleScanRequest
	(*DismantleScanResponse)(nil), // 3: boss.quadlink.v1.DismantleScanResponse
	(*QueryRequest)(nil),          // 4: boss.quadlink.v1.QueryRequest
	(*QuadLink)(nil),              // 5: boss.quadlink.v1.QuadLink
	(*ReconcileRequest)(nil),      // 6: boss.quadlink.v1.ReconcileRequest
	(*ReconcileReport)(nil),       // 7: boss.quadlink.v1.ReconcileReport
	(v1.Code)(0),                  // 8: boss.common.v1.Code
}
var file_api_proto_boss_quadlink_v1_quadlink_proto_depIdxs = []int32{
	8, // 0: boss.quadlink.v1.ScanBindResponse.code:type_name -> boss.common.v1.Code
	8, // 1: boss.quadlink.v1.DismantleScanResponse.code:type_name -> boss.common.v1.Code
	0, // 2: boss.quadlink.v1.QuadLinkService.ScanBind:input_type -> boss.quadlink.v1.ScanBindRequest
	2, // 3: boss.quadlink.v1.QuadLinkService.DismantleScan:input_type -> boss.quadlink.v1.DismantleScanRequest
	4, // 4: boss.quadlink.v1.QuadLinkService.Query:input_type -> boss.quadlink.v1.QueryRequest
	6, // 5: boss.quadlink.v1.QuadLinkService.Reconcile:input_type -> boss.quadlink.v1.ReconcileRequest
	1, // 6: boss.quadlink.v1.QuadLinkService.ScanBind:output_type -> boss.quadlink.v1.ScanBindResponse
	3, // 7: boss.quadlink.v1.QuadLinkService.DismantleScan:output_type -> boss.quadlink.v1.DismantleScanResponse
	5, // 8: boss.quadlink.v1.QuadLinkService.Query:output_type -> boss.quadlink.v1.QuadLink
	7, // 9: boss.quadlink.v1.QuadLinkService.Reconcile:output_type -> boss.quadlink.v1.ReconcileReport
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_boss_quadlink_v1_quadlink_proto_init() }
func file_api_proto_boss_quadlink_v1_quadlink_proto_init() {
	if File_api_proto_boss_quadlink_v1_quadlink_proto != nil {
		return
	}
	file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes[4].OneofWrappers = []any{
		(*QueryRequest_AssetId)(nil),
		(*QueryRequest_CustomerId)(nil),
		(*QueryRequest_PortId)(nil),
		(*QueryRequest_AddressId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_boss_quadlink_v1_quadlink_proto_rawDesc), len(file_api_proto_boss_quadlink_v1_quadlink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_boss_quadlink_v1_quadlink_proto_goTypes,
		DependencyIndexes: file_api_proto_boss_quadlink_v1_quadlink_proto_depIdxs,
		MessageInfos:      file_api_proto_boss_quadlink_v1_quadlink_proto_msgTypes,
	}.Build()
	File_api_proto_boss_quadlink_v1_quadlink_proto = out.File
	file_api_proto_boss_quadlink_v1_quadlink_proto_goTypes = nil
	file_api_proto_boss_quadlink_v1_quadlink_proto_depIdxs = nil
}
