// boss/quadlink/v1 —— 四码合一服务契约(师傅端→服务端,阶段6/W5)。
// 语义:扫码绑定校验(不一致拒)、拆机必扫码、四码反查、对账。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/boss/quadlink/v1/quadlink.proto

package quadlinkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuadLinkService_ScanBind_FullMethodName      = "/boss.quadlink.v1.QuadLinkService/ScanBind"
	QuadLinkService_DismantleScan_FullMethodName = "/boss.quadlink.v1.QuadLinkService/DismantleScan"
	QuadLinkService_Query_FullMethodName         = "/boss.quadlink.v1.QuadLinkService/Query"
	QuadLinkService_Reconcile_FullMethodName     = "/boss.quadlink.v1.QuadLinkService/Reconcile"
)

// QuadLinkServiceClient is the client API for QuadLinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// QuadLinkService 四码合一服务。
type QuadLinkServiceClient interface {
	// ScanBind 扫码绑定(环节9):实物 EPC ↔ 预绑定核对;不一致返回 CODE_SCAN_MISMATCH。
	ScanBind(ctx context.Context, in *ScanBindRequest, opts ...grpc.CallOption) (*ScanBindResponse, error)
	// DismantleScan 拆机扫码解绑(强制):不扫码返回 CODE_INVALID_PARAM,不一致返回 CODE_SCAN_MISMATCH。
	DismantleScan(ctx context.Context, in *DismantleScanRequest, opts ...grpc.CallOption) (*DismantleScanResponse, error)
	// Query 任一码反查四码(资产/客户/端口/地址任一 ID)。
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QuadLink, error)
	// Reconcile 四码对账任务(定时触发):成员缺失置 CONFLICT。
	Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (*ReconcileReport, error)
}

type quadLinkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuadLinkServiceClient(cc grpc.ClientConnInterface) QuadLinkServiceClient {
	return &quadLinkServiceClient{cc}
}

func (c *quadLinkServiceClient) ScanBind(ctx context.Context, in *ScanBindRequest, opts ...grpc.CallOption) (*ScanBindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanBindResponse)
	err := c.cc.Invoke(ctx, QuadLinkService_ScanBind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quadLinkServiceClient) DismantleScan(ctx context.Context, in *DismantleScanRequest, opts ...grpc.CallOption) (*DismantleScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DismantleScanResponse)
	err := c.cc.Invoke(ctx, QuadLinkService_DismantleScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quadLinkServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QuadLink, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuadLink)
	err := c.cc.Invoke(ctx, QuadLinkService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quadLinkServiceClient) Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (*ReconcileReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileReport)
	err := c.cc.Invoke(ctx, QuadLinkService_Reconcile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuadLinkServiceServer is the server API for QuadLinkService service.
// All implementations must embed UnimplementedQuadLinkServiceServer
// for forward compatibility.
//
// QuadLinkService 四码合一服务。
type QuadLinkServiceServer interface {
	// ScanBind 扫码绑定(环节9):实物 EPC ↔ 预绑定核对;不一致返回 CODE_SCAN_MISMATCH。
	ScanBind(context.Context, *ScanBindRequest) (*ScanBindResponse, error)
	// DismantleScan 拆机扫码解绑(强制):不扫码返回 CODE_INVALID_PARAM,不一致返回 CODE_SCAN_MISMATCH。
	DismantleScan(context.Context, *DismantleScanRequest) (*DismantleScanResponse, error)
	// Query 任一码反查四码(资产/客户/端口/地址任一 ID)。
	Query(context.Context, *QueryRequest) (*QuadLink, error)
	// Reconcile 四码对账任务(定时触发):成员缺失置 CONFLICT。
	Reconcile(context.Context, *ReconcileRequest) (*ReconcileReport, error)
	mustEmbedUnimplementedQuadLinkServiceServer()
}

// UnimplementedQuadLinkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuadLinkServiceServer struct{}

func (UnimplementedQuadLinkServiceServer) ScanBind(context.Context, *ScanBindRequest) (*ScanBindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanBind not implemented")
}
func (UnimplementedQuadLinkServiceServer) DismantleScan(context.Context, *DismantleScanRequest) (*DismantleScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DismantleScan not implemented")
}
func (UnimplementedQuadLinkServiceServer) Query(context.Context, *QueryRequest) (*QuadLink, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedQuadLinkServiceServer) Reconcile(context.Context, *ReconcileRequest) (*ReconcileReport, error) {
	return nil, status.Error(codes.Unimplemented, "method Reconcile not implemented")
}
func (UnimplementedQuadLinkServiceServer) mustEmbedUnimplementedQuadLinkServiceServer() {}
func (UnimplementedQuadLinkServiceServer) testEmbeddedByValue()                         {}

// UnsafeQuadLinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuadLinkServiceServer will
// result in compilation errors.
type UnsafeQuadLinkServiceServer interface {
	mustEmbedUnimplementedQuadLinkServiceServer()
}

func RegisterQuadLinkServiceServer(s grpc.ServiceRegistrar, srv QuadLinkServiceServer) {
	// If the following call panics, it indicates UnimplementedQuadLinkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuadLinkService_ServiceDesc, srv)
}

func _QuadLinkService_ScanBind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanBindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuadLinkServiceServer).ScanBind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuadLinkService_ScanBind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuadLinkServiceServer).ScanBind(ctx, req.(*ScanBindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuadLinkService_DismantleScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DismantleScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuadLinkServiceServer).DismantleScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuadLinkService_DismantleScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuadLinkServiceServer).DismantleScan(ctx, req.(*DismantleScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuadLinkService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuadLinkServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuadLinkService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuadLinkServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuadLinkService_Reconcile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuadLinkServiceServer).Reconcile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuadLinkService_Reconcile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuadLinkServiceServer).Reconcile(ctx, req.(*ReconcileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuadLinkService_ServiceDesc is the grpc.ServiceDesc for QuadLinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuadLinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "boss.quadlink.v1.QuadLinkService",
	HandlerType: (*QuadLinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScanBind",
			Handler:    _QuadLinkService_ScanBind_Handler,
		},
		{
			MethodName: "DismantleScan",
			Handler:    _QuadLinkService_DismantleScan_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _QuadLinkService_Query_Handler,
		},
		{
			MethodName: "Reconcile",
			Handler:    _QuadLinkService_Reconcile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/boss/quadlink/v1/quadlink.proto",
}
